python ./train_pc.py \
  --exp_name 'pc_vae_display' \
  --category 'Display' \
  --data_path '../data/partnetdata/display_hier' \
  --train_dataset 'train.txt' \
  --val_dataset 'val.txt' \
  --epochs 200 \
  --model_version 'model_pc' \
  --load_geo \
  --part_pc_exp_name 'part_pc_vae_display' \
  --part_pc_model_epoch 954
